---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Ensure Apache is running and enabled
      systemd:
        name: apache2
        state: started
        enabled: true

    - name: Configure Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'

    - name: Change default virtual host to port 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^<VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'

    - name: Restart Apache to apply changes
      systemd:
        name: apache2
        state: restarted

    - name: Create a simple HTML page on VM1 and VM2
      copy:
        content: |
          <html>
          <body>
            <h1>Hello World from SJSU-{{ inventory_hostname == "VM1" | ternary("1", "2") }}</h1>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

